export const blockNumber = 1000;
export const mineNumber = 150;
export const xNumber = 10;
export const yNumber = 100;
export const windowWidth = window.outerWidth;
export const windowHeight = window.outerHeight;
export const containerStyle = {width: windowWidth < 400 ? windowWidth : 400};
export const size = containerStyle.width / 10;
export const blockStyle = {width: size, height: size};
